#!/bin/bash

set -e


psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    DROP USER IF EXISTS $PHX_DB_USERNAME;
    DROP TABLE IF EXISTS $PHX_DB;
    CREATE USER $PHX_DB_USERNAME WITH ENCRYPTED PASSWORD '$PHX_DB_PASSWORD';
    CREATE DATABASE $PHX_DB OWNER $PHX_DB_USERNAME;
    GRANT ALL PRIVILEGES ON DATABASE $PHX_DB TO $PHX_DB_USERNAME;
    ALTER USER $PHX_DB_USERNAME CREATEDB;
EOSQL

